// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SGRIA.Infrastructure.Persistence;

#nullable disable

namespace SGRIA.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126232517_AddIndicesOptimizacion")]
    partial class AddIndicesOptimizacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SGRIA.Domain.Entities.ItemMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ItmId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ItmActivo");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ItmCategoria");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("ItmDescripcion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ItmImagenUrl");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ItmNombre");

                    b.Property<decimal?>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ItmPrecio");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("ItmResId");

                    b.HasKey("Id");

                    b.HasIndex("Categoria");

                    b.HasIndex("RestauranteId");

                    b.HasIndex("RestauranteId", "Activo");

                    b.ToTable("items_menu", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.ItemMenuAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AliId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("AliActivo");

                    b.Property<string>("AliasTexto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("AliTexto");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("AliItmId");

                    b.HasKey("Id");

                    b.HasIndex("ItemMenuId");

                    b.HasIndex("AliasTexto", "Activo");

                    b.ToTable("items_menu_alias", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Mesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MesId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("MesActiva");

                    b.Property<int>("CantidadSillas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("MesCantidadSillas");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("MesFchaModificacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("MesNumero");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("MesQrToken");

                    b.Property<int>("RestauranteId")
                        .HasColumnType("integer")
                        .HasColumnName("MesResId");

                    b.HasKey("Id");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.HasIndex("RestauranteId", "Numero");

                    b.ToTable("mesas", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.NotificacionCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NclId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Atendida")
                        .HasColumnType("boolean")
                        .HasColumnName("NclAtendida");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("NclFechaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("MesId");

                    b.HasKey("Id");

                    b.HasIndex("MesaId");

                    b.ToTable("notificaciones_cliente", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Restaurante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ResId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ResActivo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ResFchaCreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ResNombre");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("America/Montevideo")
                        .HasColumnName("ResTimeZone");

                    b.HasKey("Id");

                    b.HasIndex("Nombre");

                    b.ToTable("restaurantes", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SenalPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("PedId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("PedCantidad");

                    b.Property<decimal?>("Confianza")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("PedConfianza");

                    b.Property<DateTime>("FechaHoraConfirmacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("PedFchaHoraConfirmacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IngresadoPor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Cliente")
                        .HasColumnName("PedIngresadoPor");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("PedItmId");

                    b.Property<int>("SesionMesaId")
                        .HasColumnType("integer")
                        .HasColumnName("PedSesId");

                    b.HasKey("Id");

                    b.HasIndex("FechaHoraConfirmacion");

                    b.HasIndex("ItemMenuId");

                    b.HasIndex("SesionMesaId");

                    b.HasIndex("ItemMenuId", "FechaHoraConfirmacion");

                    b.ToTable("senales_pedido", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SenalRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RatId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("RatFchaHora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Puntaje")
                        .HasColumnType("smallint")
                        .HasColumnName("RatPuntaje");

                    b.Property<int>("SenalPedidoId")
                        .HasColumnType("integer")
                        .HasColumnName("RatPedId");

                    b.HasKey("Id");

                    b.HasIndex("FechaHora");

                    b.HasIndex("SenalPedidoId")
                        .IsUnique();

                    b.HasIndex("Puntaje", "FechaHora");

                    b.ToTable("senales_rating", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SesionMesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SesId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CantidadPersonas")
                        .HasColumnType("integer")
                        .HasColumnName("SesCantidadPersonas");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SesFchaHoraFin");

                    b.Property<DateTime>("FechaHoraInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("SesFchaHoraInicio")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MesaId")
                        .HasColumnType("integer")
                        .HasColumnName("SesMesId");

                    b.Property<string>("Origen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("QR")
                        .HasColumnName("SesOrigen");

                    b.HasKey("Id");

                    b.HasIndex("FechaHoraInicio");

                    b.HasIndex("MesaId");

                    b.HasIndex("MesaId", "FechaHoraFin");

                    b.ToTable("sesiones_mesa", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.TagRapido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TagId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("TagActivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("TagNombre");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TagTipo");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Activo");

                    b.ToTable("tags_rapido", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.VotoTagItemMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("VtiId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("VtiFchaHora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ItemMenuId")
                        .HasColumnType("integer")
                        .HasColumnName("VtiItmId");

                    b.Property<int>("SesionMesaId")
                        .HasColumnType("integer")
                        .HasColumnName("VtiSesId");

                    b.Property<int>("TagRapidoId")
                        .HasColumnType("integer")
                        .HasColumnName("VtiTagId");

                    b.Property<short>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("VtiValor");

                    b.HasKey("Id");

                    b.HasIndex("ItemMenuId");

                    b.HasIndex("TagRapidoId");

                    b.HasIndex("SesionMesaId", "ItemMenuId", "TagRapidoId")
                        .IsUnique();

                    b.ToTable("votos_tag_item_menu", (string)null);
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.ItemMenu", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("ItemsMenu")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.ItemMenuAlias", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.ItemMenu", "ItemMenu")
                        .WithMany("Aliases")
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMenu");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Mesa", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.Restaurante", "Restaurante")
                        .WithMany("Mesas")
                        .HasForeignKey("RestauranteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Restaurante");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.NotificacionCliente", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SenalPedido", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.ItemMenu", "ItemMenu")
                        .WithMany("SenalesPedido")
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGRIA.Domain.Entities.SesionMesa", "SesionMesa")
                        .WithMany("SenalesPedido")
                        .HasForeignKey("SesionMesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemMenu");

                    b.Navigation("SesionMesa");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SenalRating", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.SenalPedido", "SenalPedido")
                        .WithOne("Rating")
                        .HasForeignKey("SGRIA.Domain.Entities.SenalRating", "SenalPedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SenalPedido");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SesionMesa", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.Mesa", "Mesa")
                        .WithMany("Sesiones")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.VotoTagItemMenu", b =>
                {
                    b.HasOne("SGRIA.Domain.Entities.ItemMenu", "ItemMenu")
                        .WithMany("VotosTag")
                        .HasForeignKey("ItemMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGRIA.Domain.Entities.SesionMesa", "SesionMesa")
                        .WithMany("VotosTag")
                        .HasForeignKey("SesionMesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGRIA.Domain.Entities.TagRapido", "TagRapido")
                        .WithMany("Votos")
                        .HasForeignKey("TagRapidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemMenu");

                    b.Navigation("SesionMesa");

                    b.Navigation("TagRapido");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.ItemMenu", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("SenalesPedido");

                    b.Navigation("VotosTag");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Mesa", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.Restaurante", b =>
                {
                    b.Navigation("ItemsMenu");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SenalPedido", b =>
                {
                    b.Navigation("Rating");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.SesionMesa", b =>
                {
                    b.Navigation("SenalesPedido");

                    b.Navigation("VotosTag");
                });

            modelBuilder.Entity("SGRIA.Domain.Entities.TagRapido", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
